name: DAST Scan
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      issues: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          # Pointing to your live EC2 Public IP
          target: 'http://18.234.200.202'
          token: ${{ secrets.GITHUB_TOKEN }}
          # -j generates a JSON report for GitHub Security Tab
          # -r generates the HTML report
          cmd_options: '-r report.html'

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: ZAP-Security-Report
          path: report.html